name: Integración Continua Pollería Latina

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: Polleria_Latina_DB
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' 
        distribution: 'temurin'
        cache: maven
        
    - name: Dar permisos a Maven wrapper
      run: chmod +x ./mvnw
      
    - name: Ejecutar pruebas y compilar
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: Polleria_Latina_DB
        DB_USERNAME: postgres
        DB_PASSWORD: 123456
        JWT_SECRET: secreto_generico_para_pasar_las_pruebas_en_ci
        MAIL_USERNAME: test@test.com
        MAIL_PASSWORD: test
      run: ./mvnw clean verify -DskipTests 